In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/machine-predictive-maintenance-classification/predictive_maintenance.csv


In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [5]:
# Inspect the column names
print(df.columns)

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Target', 'Failure Type'],
      dtype='object')


In [10]:
# Convert 'Product ID' and 'Type' into numerical values
df['Product ID'] = df['Product ID'].astype('category').cat.codes
df['Type'] = df['Type'].astype('category').cat.codes

# Split dataset into features and target
X = df.drop(['UDI', 'Target', 'Failure Type'], axis=1)
y = df['Target']

# Normalize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

LOGISTIC REGRESSION

In [11]:
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)

print("Logistic Regression")
print(f"Accuracy: {accuracy_score(y_test, y_pred_log_reg) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

Logistic Regression
Accuracy: 97.25%
[[1930    9]
 [  46   15]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1939
           1       0.62      0.25      0.35        61

    accuracy                           0.97      2000
   macro avg       0.80      0.62      0.67      2000
weighted avg       0.97      0.97      0.97      2000



DECISION TREE CLASSIFIER

In [12]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

print("Decision Tree")
print(f"Accuracy: {accuracy_score(y_test, y_pred_dt) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree
Accuracy: 97.80%
[[1910   29]
 [  15   46]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1939
           1       0.61      0.75      0.68        61

    accuracy                           0.98      2000
   macro avg       0.80      0.87      0.83      2000
weighted avg       0.98      0.98      0.98      2000



RANDOM FOREST CLASSIFIER

In [13]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

Random Forest
Accuracy: 98.45%
[[1931    8]
 [  23   38]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1939
           1       0.83      0.62      0.71        61

    accuracy                           0.98      2000
   macro avg       0.91      0.81      0.85      2000
weighted avg       0.98      0.98      0.98      2000



GRADING BOOSTING CLASSIFIER

In [14]:
gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

print("Gradient Boosting")
print(f"Accuracy: {accuracy_score(y_test, y_pred_gb) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))

Gradient Boosting
Accuracy: 98.20%
[[1930    9]
 [  27   34]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1939
           1       0.79      0.56      0.65        61

    accuracy                           0.98      2000
   macro avg       0.89      0.78      0.82      2000
weighted avg       0.98      0.98      0.98      2000



SUPPORT VECTOR MACHINE

In [18]:
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Support Vector Machine")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Support Vector Machine
Accuracy: 97.65%
[[1935    4]
 [  43   18]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1939
           1       0.82      0.30      0.43        61

    accuracy                           0.98      2000
   macro avg       0.90      0.65      0.71      2000
weighted avg       0.97      0.98      0.97      2000



K-Nearest Neighbors (KNN)

In [16]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

print("K-Nearest Neighbors")
print(f"Accuracy: {accuracy_score(y_test, y_pred_knn) * 100:.2f}%")
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

K-Nearest Neighbors
Accuracy: 97.70%
[[1933    6]
 [  40   21]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1939
           1       0.78      0.34      0.48        61

    accuracy                           0.98      2000
   macro avg       0.88      0.67      0.73      2000
weighted avg       0.97      0.98      0.97      2000



COMPARISION

In [19]:
models = ['Logistic Regression', 'Decision Tree', 'Random Forest', 'Gradient Boosting', 'SVM', 'KNN']
accuracies = [accuracy_score(y_test, y_pred_log_reg),
              accuracy_score(y_test, y_pred_dt),
              accuracy_score(y_test, y_pred_rf),
              accuracy_score(y_test, y_pred_gb),
              accuracy_score(y_test, y_pred_svm),
              accuracy_score(y_test, y_pred_knn)]

for model, accuracy in zip(models, accuracies):
    print(f"{model}: {accuracy * 100:.2f}%")


Logistic Regression: 97.25%
Decision Tree: 97.80%
Random Forest: 98.45%
Gradient Boosting: 98.20%
SVM: 97.65%
KNN: 97.70%
